name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username : ${{ secrets.DOCKERHUB_USERNAME }}
          password : ${{ secrets.RECIPE_APP_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app -c "flake8"